### ISSUE TITLE
(OOC) H370 Hackintosh

### ISSUE THREAD

**Issue by macmeister1967** [ktg5/csgo-autoexec#1]
Hi Kyle,

I tried to reply via your H370 Hack page, but it is archived now :-(

I have a fully working OpenCore EFI folder for that identical machine (H370 HD3 + i7-8700 + RX 580) booting both macOS Mojave and Win 10. Everything works, including shutdown, restart and sleep/wake. Bluetooth + WiFi (BCM943602CS) card fully working as natively supported. It is only OpenCore 0.6.0, but it still works fine.

If you are interested, please reply to this message, I'll send you a link to my EFI folder.

**Comment by ktg5** [comment]
Hello,

Thanks for your interest in my past Hackintosh stuff. Unfortunately, I'm not in the Hackintosh scene anymore -- which is why those projects are archived if you didn't see the README.md.

I was having a lot of issues with the MOBO because of all the patches I still had to do and things I couldn't fix like upgrading to macOS 11. I've switched to a M1 Mac Mini about a year ago which runs perfectly. 

You can create your own fork of the repo if you'd like to and add your own stuff from there, but I won't be editing the repo anytime soon.

**Comment by macmeister1967** [comment]
It is nearly patch-free... except for fixing the NVRAM issue (with
SSDT-PCM.aml) there are no other patches required...

I converted my existing Clover install to OpenCore, and it worked first
try... sadly, trying to use any newer OpenCore version (0.7.5/0.7.6) is a
nightmare, with macOS never even BEGINNING to boot... and it even
blue-screens Win10  in some instances.

Once again, my fully working Gigabyte H370 HD3 + i7-8700 + Sapphire Pulse
RX 580 8GB is running smoothly with no patches.

I am even using all prebuilt APCI files too... namely:

SSDT-AWAC.aml
SSDT-EC-USBX.aml
SSDT-PLUG-DRTNIA.aml
SSDT-PMC.aml
SSDT-UIAC.aml  (my custom USB map for USBInjectAll.kext)

Anyways, hope you are enjoying the M1... I am loving macOS Steam with all
my games still working under Mojave (dang 32 bit!!)
